### ISSUE TITLE
运行后，抱这个错误

### ISSUE THREAD

**Issue by chunjingqiu** [walkor/workerman-flappy-bird#1]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Event' does not have a method 'onConnect' in /var/www/workerman-flappy-bird/applications/Flappybird/Bootstrap/BusinessWorker.php on line 125

**Comment by walkor** [comment]
这个是老版本的workerman封装的，内部有个Event类，和Event扩展冲突了。需要把Event扩展卸载掉
